version: '3.7'

services:
# --------------------- SYSTEM TEST ----------------------------------------
  system-test:
    image: open-data-service/ods-main/system-test
    depends_on:
      - mock-server
    build:
      context: ./system-test/

    environment:
      CORE_API: http://core:8080
      STORAGE_API: http://storage:3000
      TRANSFORMATION_API: http://transformation:8080
      SCHEDULER_API: http://scheduler:8080
      ADAPTER_API: http://adapter:8080
      MOCK_SERVER_API: http://mock-server:8080

  mock-server:
    build:
      context: ./system-test/
      dockerfile: Dockerfile.mocks

    environment:
      MOCK_SERVER_PORT: 8080

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.to-mock-server.rule=PathPrefix(`/api/system-tests/mock-server/`)"
      - "traefik.http.routers.to-mock-server.middlewares=mock-server-stripprefix@docker"
      - "traefik.http.middlewares.mock-server-stripprefix.stripprefix.prefixes=/api/mock-server"
