# Overwrite service configurations of global docker-compose.yml
# for System-Testing, including MOCK and SYSTEM-TEST SERVICE.
# can be used locally or in the CI ENVIRONMENT.

version: '3.7'

services:
# --------------------- SYSTEM TEST ----------------------------------------
  mock-server:
    build:
      context: ./system-test/
      dockerfile: Dockerfile.mocks

    environment:
      MOCK_SERVER_PORT: 8080

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.to-mock-server.rule=PathPrefix(`/api/system-tests/mock-server/`)"
      - "traefik.http.routers.to-mock-server.middlewares=mock-server-stripprefix@docker"
      - "traefik.http.middlewares.mock-server-stripprefix.stripprefix.prefixes=/api/system-tests/mock-server"

  rabbitmq:
    ports: 5672:5672