apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ods
      service: scheduler
  template:
    metadata:
      labels:
        app: ods
        service: scheduler
    spec:
      containers:
        - name: scheduler-service
          image: jvalue/open-data-service:scheduler-latest
          imagePullPolicy: Always

          env:
            - name: CONFIG_SERVICE_URL
              value: "http://core-service:8080"
            - name: ADAPTER_SERVICE_URL
              value: "http://adapter-service:8080"
            - name: TRANSFORMATION_SERVICE_URL
              value: "http://transformation-service:8080"
            - name: STORAGE_SERVICE_URL
              value: "http://storage-db-service:3000"
            - name: INITIAL_CONNECTION_RETRIES
              value: "20"
            - name: INITIAL_CONNECTION_RETRY_BACKOFF
              value: "5000"

          ports:
            - containerPort: 8080

          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10

          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
