name: UI Build & Test & Publish

on: [push]

jobs:
  ui-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        run: |
          cd ui
          docker build -t docker.pkg.github.com/${{ github.repository }}/ui .

      - name: Push to registry
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/ui

          UI_VERSION=$(cat package.json | grep "version" | awk '{print $2}' | sed 's/[,"]//g')

          docker tag $IMAGE_ID $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
